// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ASIS

#include "../ui.h"
extern lv_font_t  *myFont14;
extern lv_font_t  *myFont18;
extern lv_font_t  *myFont22;
extern lv_font_t  *myFont26;
extern lv_font_t  *myFont30;


void ui_screen_ha_data_screen_init(void)
{
ui_screen_ha_data = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_ha_data, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screen_ha_data, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screen_ha_data, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ha_data_wifi_btn = lv_btn_create(ui_screen_ha_data);
lv_obj_set_width( ui_ha_data_wifi_btn, 60);
lv_obj_set_height( ui_ha_data_wifi_btn, 60);
lv_obj_set_x( ui_ha_data_wifi_btn, -10 );
lv_obj_set_y( ui_ha_data_wifi_btn, 10 );
lv_obj_set_align( ui_ha_data_wifi_btn, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_ha_data_wifi_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ha_data_wifi_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ha_data_wifi_btn, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ha_data_wifi_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ha_data_wifi_btn, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_ha_data_wifi_st = lv_img_create(ui_ha_data_wifi_btn);
lv_img_set_src(ui_ha_data_wifi_st, &ui_img_wifi_disconet_png);
lv_obj_set_width( ui_ha_data_wifi_st, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ha_data_wifi_st, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ha_data_wifi_st, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_ha_data_wifi_st, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ha_data_wifi_st, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ha_data_time = lv_label_create(ui_screen_ha_data);
lv_obj_set_width( ui_ha_data_time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ha_data_time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ha_data_time, 30 );
lv_obj_set_y( ui_ha_data_time, 20 );
lv_label_set_text(ui_ha_data_time,"21:20");
lv_obj_set_style_text_font(ui_ha_data_time, &ui_font_font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_screen_home_data_label = lv_label_create(ui_screen_ha_data);
lv_obj_set_width( ui_screen_home_data_label, 316);
lv_obj_set_height( ui_screen_home_data_label, 38);
lv_obj_set_x( ui_screen_home_data_label, 82 );
lv_obj_set_y( ui_screen_home_data_label, 58 );
lv_label_set_text(ui_screen_home_data_label,"9A HR & COM");
lv_obj_set_style_text_color(ui_screen_home_data_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_screen_home_data_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_screen_home_data_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_screen_home_data_label, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_com_all = lv_btn_create(ui_screen_ha_data);
lv_obj_set_width( ui_com_all, 214);
lv_obj_set_height( ui_com_all, 164);
lv_obj_set_x( ui_com_all, 22 );
lv_obj_set_y( ui_com_all, 96 );
lv_obj_add_flag( ui_com_all, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_com_all, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_com_all, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_com_all, 20, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_com_all, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_com_all, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_com_all, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_com_all, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_add_flag(ui_com_all, LV_OBJ_FLAG_CHECKABLE);


ui_com_all_logo = lv_img_create(ui_com_all);
lv_img_set_src(ui_com_all_logo, &ui_img_ic_switch2_off_png);
lv_obj_set_width( ui_com_all_logo, LV_SIZE_CONTENT);  /// 45
lv_obj_set_height( ui_com_all_logo, LV_SIZE_CONTENT);   /// 45
lv_obj_set_x( ui_com_all_logo, 40 );
lv_obj_set_y( ui_com_all_logo, 6 );
lv_obj_add_flag( ui_com_all_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_com_all_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_com_all_label = lv_label_create(ui_com_all);
lv_obj_set_width( ui_com_all_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_com_all_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_com_all_label, 0 );
lv_obj_set_y( ui_com_all_label, -5 );
lv_obj_set_align( ui_com_all_label, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_com_all_label, "COM");
lv_obj_set_style_text_color(ui_com_all_label, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_com_all_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_com_all_label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);


ui_hr_all = lv_btn_create(ui_screen_ha_data);
lv_obj_set_width( ui_hr_all, 214);
lv_obj_set_height( ui_hr_all, 164);
lv_obj_set_x( ui_hr_all, 244 );
lv_obj_set_y( ui_hr_all, 96 );
lv_obj_add_flag( ui_hr_all, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_hr_all, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_hr_all, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_hr_all, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_hr_all, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_add_flag(ui_hr_all, LV_OBJ_FLAG_CHECKABLE);


ui_hr_all_logo = lv_img_create(ui_hr_all);
lv_img_set_src(ui_hr_all_logo, &ui_img_ic_switch2_on_png);
lv_obj_set_width( ui_hr_all_logo, LV_SIZE_CONTENT);  /// 45
lv_obj_set_height( ui_hr_all_logo, LV_SIZE_CONTENT);   /// 45
lv_obj_set_x( ui_hr_all_logo, 40 );
lv_obj_set_y( ui_hr_all_logo, 6 );
lv_obj_add_flag( ui_hr_all_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_hr_all_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_hr_all_label = lv_label_create(ui_hr_all);
lv_obj_set_width( ui_hr_all_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hr_all_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hr_all_label, 0 );
lv_obj_set_y( ui_hr_all_label, -5 );
lv_obj_set_align( ui_hr_all_label, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_hr_all_label, "HR");
lv_obj_set_style_text_color(ui_hr_all_label, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_hr_all_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_hr_all_label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);


ui_rest_01 = lv_btn_create(ui_screen_ha_data);
lv_obj_set_width( ui_rest_01, 214);
lv_obj_set_height( ui_rest_01, 78);
lv_obj_set_x( ui_rest_01, 22 );
lv_obj_set_y( ui_rest_01, 268 );
lv_obj_add_flag( ui_rest_01, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_rest_01, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_rest_01, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_rest_01, 20, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_rest_01, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rest_01, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rest_01, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_rest_01, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_add_flag(ui_rest_01, LV_OBJ_FLAG_CHECKABLE);





ui_rest_01_logo = lv_img_create(ui_rest_01);
lv_img_set_src(ui_rest_01_logo, &ui_img_ic_switch1_off_png);
lv_obj_set_x( ui_rest_01_logo, 125 );
lv_obj_set_y( ui_rest_01_logo, 2 );
lv_obj_add_flag( ui_rest_01_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_rest_01_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rest_01_label = lv_label_create(ui_rest_01);
lv_obj_set_width( ui_rest_01_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rest_01_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_rest_01_label, 5 );
lv_obj_set_y( ui_rest_01_label, 12 );
lv_label_set_text(ui_rest_01_label, "休息区");
lv_obj_set_style_text_color(ui_rest_01_label, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rest_01_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rest_01_label, &myFont30, LV_PART_MAIN| LV_STATE_DEFAULT);


ui_rest_02 = lv_btn_create(ui_screen_ha_data);
lv_obj_set_width( ui_rest_02, 214);
lv_obj_set_height( ui_rest_02, 78);
lv_obj_set_x( ui_rest_02, 22 );
lv_obj_set_y( ui_rest_02, 354 );
lv_obj_add_flag( ui_rest_02, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_rest_02, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_rest_02, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_rest_02, 20, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_rest_02, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rest_02, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rest_02, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_rest_02, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_add_flag(ui_rest_02, LV_OBJ_FLAG_CHECKABLE);

ui_rest_02_logo = lv_img_create(ui_rest_02);
lv_img_set_src(ui_rest_02_logo, &ui_img_ic_switch1_off_png);
lv_obj_set_x( ui_rest_02_logo, 125 );
lv_obj_set_y( ui_rest_02_logo, 2 );
lv_obj_add_flag( ui_rest_02_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_rest_02_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_rest_02_label = lv_label_create(ui_rest_02);
lv_obj_set_width( ui_rest_02_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rest_02_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_rest_02_label, 5 );
lv_obj_set_y( ui_rest_02_label, 12 );
lv_label_set_text(ui_rest_02_label, "财务走廊");
lv_obj_set_style_text_color(ui_rest_02_label, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rest_02_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rest_02_label, &myFont30, LV_PART_MAIN| LV_STATE_DEFAULT);


ui_front_01 = lv_btn_create(ui_screen_ha_data);
lv_obj_set_width( ui_front_01, 214);
lv_obj_set_height( ui_front_01, 78);
lv_obj_set_x( ui_front_01, 244 );
lv_obj_set_y( ui_front_01, 268 );
lv_obj_add_flag( ui_front_01, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_front_01, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_front_01, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_front_01, 20, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_front_01, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_front_01, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_front_01, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_front_01, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_add_flag(ui_front_01, LV_OBJ_FLAG_CHECKABLE);

ui_front_01_logo = lv_img_create(ui_front_01);
lv_img_set_src(ui_front_01_logo, &ui_img_ic_switch1_off_png);
lv_obj_set_x( ui_front_01_logo, 125 );
lv_obj_set_y( ui_front_01_logo, 2 );
lv_obj_add_flag( ui_front_01_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_front_01_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_front_01_label = lv_label_create(ui_front_01);
lv_obj_set_width( ui_front_01_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_front_01_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_front_01_label, 5 );
lv_obj_set_y( ui_front_01_label, 12 );
lv_label_set_text(ui_front_01_label, "前  台");
lv_obj_set_style_text_color(ui_front_01_label, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_front_01_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_front_01_label, &myFont30, LV_PART_MAIN| LV_STATE_DEFAULT);




ui_front_02 = lv_btn_create(ui_screen_ha_data);
lv_obj_set_width( ui_front_02, 214);
lv_obj_set_height( ui_front_02, 78);
lv_obj_set_x( ui_front_02, 244 );
lv_obj_set_y( ui_front_02, 354 );
lv_obj_add_flag( ui_front_02, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_front_02, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_front_02, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_front_02, 20, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_front_02, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_front_02, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_front_02, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_front_02, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_add_flag(ui_front_02, LV_OBJ_FLAG_CHECKABLE);

ui_front_02_logo = lv_img_create(ui_front_02);
lv_img_set_src(ui_front_02_logo, &ui_img_ic_switch1_off_png);
lv_obj_set_x( ui_front_02_logo, 125 );
lv_obj_set_y( ui_front_02_logo, 2 );
lv_obj_add_flag( ui_front_02_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_front_02_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_front_02_label = lv_label_create(ui_front_02);
lv_obj_set_width( ui_front_02_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_front_02_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_front_02_label, 5 );
lv_obj_set_y( ui_front_02_label, 12 );
lv_label_set_text(ui_front_02_label, "培训室");
lv_obj_set_style_text_color(ui_front_02_label, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_front_02_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_front_02_label, &myFont30, LV_PART_MAIN| LV_STATE_DEFAULT);
    creat_scrolldots(ui_screen_ha_data, 2);
}
