// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ASIS

#include "./ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_screen_ha_data
void ui_screen_ha_data_screen_init(void);
lv_obj_t *ui_screen_ha_data;
lv_obj_t *ui_ha_data_wifi_btn;
lv_obj_t *ui_ha_data_wifi_st;
lv_obj_t *ui_ha_data_time;
lv_obj_t *ui_screen_home_data_label;

lv_obj_t *ui_hr_all;
lv_obj_t *ui_hr_all_logo;
lv_obj_t *ui_hr_all_label;

lv_obj_t *ui_com_all;
lv_obj_t *ui_com_all_logo;
lv_obj_t *ui_com_all_label;

lv_obj_t *ui_rest_01;
lv_obj_t *ui_rest_01_logo;
lv_obj_t *ui_rest_01_label;

lv_obj_t *ui_rest_02;
lv_obj_t *ui_rest_02_logo;
lv_obj_t *ui_rest_02_label;


lv_obj_t *ui_front_01;
lv_obj_t *ui_front_01_logo;
lv_obj_t *ui_front_01_label;


lv_obj_t *ui_front_02;
lv_obj_t *ui_front_02_logo;
lv_obj_t *ui_front_02_label;




// SCREEN: ui_screen_ha
void ui_screen_ha_screen_init(void);
lv_obj_t *ui_screen_ha;
lv_obj_t *ui_ha_wifi_btn;
lv_obj_t *ui_ha_wifi_st;
lv_obj_t *ui_ha_time;
lv_obj_t *ui_screen_home_none_lable;
lv_obj_t *ui_sensor5_btn;
lv_obj_t *ui_sensor5_logo;
lv_obj_t *ui_sensor5_label;
lv_obj_t *ui_sensor5_data;
lv_obj_t *ui_sensor5_unit;
lv_obj_t *ui_sensor6_btn;
lv_obj_t *ui_sensor6_logo;
lv_obj_t *ui_sensor6_label;
lv_obj_t *ui_sensor6_data;
lv_obj_t *ui_sensor6_unit;
lv_obj_t *ui_switch1;
lv_obj_t *ui_switch1_logo;
lv_obj_t *ui_switch1_label;
lv_obj_t *ui_switch2;
lv_obj_t *ui_switch2_logo;
lv_obj_t *ui_switch2_label;
lv_obj_t *ui_switch3;
lv_obj_t *ui_switch3_label;
lv_obj_t *ui_switch3_switch;


lv_obj_t *ui_iag_all_btn;
lv_obj_t *ui_iag_all_logo;
lv_obj_t *ui_iag_all_label;
lv_obj_t *ui_stu_all_btn;
lv_obj_t *ui_stu_all_logo;
lv_obj_t *ui_stu_all_label;
lv_obj_t *ui_stu_01_btn;
lv_obj_t *ui_stu_01_logo;
lv_obj_t *ui_stu_01_label;
lv_obj_t *ui_stu_02_btn;
lv_obj_t *ui_stu_02_logo;
lv_obj_t *ui_stu_02_label;
lv_obj_t *ui_stu_03_btn;
lv_obj_t *ui_stu_03_logo;
lv_obj_t *ui_stu_03_label;
lv_obj_t *ui_stu_04_btn;
lv_obj_t *ui_stu_04_logo;
lv_obj_t *ui_stu_04_label;
lv_obj_t *ui_stu_05_btn;
lv_obj_t *ui_iag_all_btn;
lv_obj_t *ui_iag_all_logo;
lv_obj_t *ui_iag_all_label;
lv_obj_t *ui_iag_01_btn;
lv_obj_t *ui_iag_01_logo;
lv_obj_t *ui_iag_01_label;
lv_obj_t *ui_iag_02_btn;
lv_obj_t *ui_iag_02_logo;
lv_obj_t *ui_iag_02_label;
lv_obj_t *ui_iag_03_btn;
lv_obj_t *ui_iag_03_logo;
lv_obj_t *ui_iag_03_label;
lv_obj_t *ui_iag_04_btn;
lv_obj_t *ui_iag_04_logo;
lv_obj_t *ui_iag_04_label;

// SCREEN: ui_screen_ha_ctrl
void ui_screen_ha_ctrl_screen_init(void);
lv_obj_t *ui_screen_ha_ctrl;
lv_obj_t *ui_ha_ctrl_wifi_btn;
lv_obj_t *ui_ha_ctrl_wifi_st;
lv_obj_t *ui_ha_ctrl_time;
lv_obj_t *ui_screen_home_ctrl_lable;
lv_obj_t *ui_switch4;
lv_obj_t *ui_switch4_logo;
lv_obj_t *ui_switch4_label;
lv_obj_t *ui_switch5;
lv_obj_t *ui_switch5_arc;
lv_obj_t *ui_switch5_arc_data;
lv_obj_t *ui_switch5_label;
lv_obj_t *ui_switch6;
lv_obj_t *ui_switch6_logo;
lv_obj_t *ui_switch6_label;
lv_obj_t *ui_switch7;
lv_obj_t *ui_switch7_label;
lv_obj_t *ui_switch7_switch;
lv_obj_t *ui_switch8;
lv_obj_t *ui_switch8_label;
lv_obj_t *ui_switch8_slider;



///////////////////// SCREENS ////////////////////
void ui_ha_init( void )
{
    ui_screen_ha_data_screen_init();
//    ui_screen_ha_screen_init();
//    ui_screen_ha_ctrl_screen_init();
}
